channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.1
  - r-lintr=3.1.1
  - r-ape=5.8
  - r-igraph=2.0.3
  - r-uwot=0.2.2
  - r-dbscan=1.1_12
  - r-ggrepel=0.9.5
  - r-phyr=1.1.0
  - r-logistf=1.26.0
  - r-phytools=2.1_1
  - r-rcpp=1.0.12
  - r-rcpparmadillo=0.12.8.3.0
  - r-tidyverse=2.0.0
  - r-ggtree=3.12.0
  - r-ggnewscale=0.4.10
  - r-grDevices=4.4.1
  - r-parallel=4.4.1
  - r-reshape2=1.4.4
  - r-cowplot=1.1.3
  - r-phytools=2.1_1
  - r-ggforce=0.4.2
  - r-plotly=4.10.4
  - r-cogeqc=1.8.0
  - r-Matrix=1.7_0
