channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.3
  - r-lintr=3.1.2
  - r-ape=5.8
  - r-igraph=2.0.3
  - r-uwot=0.1.16
  - r-dbscan=1.1_12
  - r-ggrepel=0.9.6
  - r-logistf=1.26.0
  - r-phytools=2.3_0
  - r-rcpp=1.0.13_1
  - r-rcpparmadillo=14.2.0_1
  - r-tidyverse=2.0.0
  - bioconductor-ggtree=3.10.0
  - r-ggnewscale=0.5.0
  - r-reshape2=1.4.4
  - r-cowplot=1.1.3
  - r-ggforce=0.4.2
  - r-plotly=4.10.4
  - bioconductor-cogeqc=1.6.0
  - r-matrix=1.6_5
  - r-jpeg=0.1_10
  - r-latticeextra=0.6_30
